import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/navbar";
import AppShell from "./components/layout/appShell";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GovBidAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppShell>
          <Navbar />
          {children}
        </AppShell>
      </body>
    </html>
  );
}
